'use strict';

/* ============================================================
 * 医询 MedAssist · 本地医疗知识库
 * 数据为常见病症/OTC 药物的公开科普信息整理，不构成医疗建议。
 * 架构参考开源项目: github.com/liuhuanyong/QASystemOnMedicalKG
 * ============================================================ */

/* 红旗急症信号 —— 命中即覆盖推荐流程, 强制就医指引 */
const RED_FLAGS = [
  { kw: ["胸痛", "胸闷", "压榨", "心绞痛"], name: "疑似心血管急症（如心梗）", action: "立即拨打 120，勿自行走动或驾车", detail: "压榨性胸痛可放射至左臂/下颌，伴冷汗、气短时风险最高。" },
  { kw: ["偏瘫", "口角歪斜", "言语不清", "一侧无力", "手脚发麻抬不起"], name: "疑似脑卒中（中风）", action: "立即拨打 120 并记录发病时间", detail: "FAST 原则：脸歪、臂垂、语乱，任一项成立立即行动，溶栓有时间窗。" },
  { kw: ["呼吸困难", "喘不上气", "喉头", "窒息", "喉咙锁住"], name: "气道 / 呼吸急症", action: "立即就医或拨打 120", detail: "过敏引发的喉头水肿可在数分钟内进展，切勿等待。" },
  { kw: ["最剧烈的头痛", "雷击样头痛", "喷射性呕吐", "炸裂"], name: "疑似蛛网膜下腔出血", action: "立即急诊", detail: "突发『一生中最剧烈』的头痛是危险信号，与普通头痛性质完全不同。" },
  { kw: ["呕血", "吐血", "黑便", "柏油样"], name: "疑似消化道出血", action: "立即急诊，禁食禁水", detail: "呕血或柏油样黑便提示上消化道出血。" },
  { kw: ["意识模糊", "叫不醒", "抽搐", "昏迷"], name: "意识障碍", action: "立即拨打 120", detail: "任何原因的意识改变都属于急症。" },
  { kw: ["高热不退", "39.5", "40度", "40℃", "高烧抽搐"], name: "高热伴危险体征", action: "立即就医", detail: "持续高热或热性惊厥需急诊评估。" },
];

/* 可能病症库 */
const DISEASES = [
  {
    id: "cold", name: "普通感冒（上呼吸道感染）",
    aliases: ["感冒", "伤风", "着凉"],
    dept: "呼吸内科 / 全科",
    kw: { "鼻塞": 3, "流涕": 3, "打喷嚏": 2, "咽痛": 2, "嗓子疼": 2, "咳嗽": 2, "低热": 2, "发热": 1, "乏力": 1, "头痛": 1, "浑身酸": 1, "鼻涕": 2 },
    otc: ["paracetamol", "compound_cold", "loquat"],
    advice: ["多休息、多饮温水", "保持室内通风与湿度", "普通感冒多为自限性，通常 5–7 天缓解"],
    redflags: ["高热持续 3 天以上", "咳脓痰、胸痛、呼吸困难", "症状一周不缓解反而加重"],
    note: "感冒由病毒引起，抗生素无效；对症缓解为主。"
  },
  {
    id: "flu", name: "流行性感冒",
    aliases: ["流感", "重感冒"],
    dept: "呼吸内科 / 发热门诊",
    kw: { "高热": 3, "全身酸痛": 3, "肌肉酸": 2, "乏力": 2, "头痛": 2, "咳嗽": 1, "流行": 2, "同事": 1, "家人": 1 },
    otc: ["paracetamol"],
    rx_note: "抗病毒药（如奥司他韦）为处方药，发病 48 小时内使用效果最好，请尽早就医由医生开具。",
    advice: ["居家休息，避免传染他人", "多补水，监测体温", "老年人和慢性病患者建议尽早就诊"],
    redflags: ["持续高热不退", "胸闷、呼吸困难", "精神萎靡"],
    note: "流感与普通感冒的区别：发热更高、全身症状更重、起病更急。"
  },
  {
    id: "pharyngitis", name: "急性咽炎 / 扁桃体炎",
    aliases: ["咽炎", "嗓子发炎", "扁桃体"],
    dept: "耳鼻喉科",
    kw: { "咽痛": 3, "嗓子疼": 3, "吞咽": 2, "咽干": 2, "扁桃体": 3, "发热": 1, "声音哑": 1 },
    otc: ["loquat", "paracetamol"],
    advice: ["淡盐水漱口", "温凉流质饮食，避免辛辣", "少用声"],
    redflags: ["扁桃体化脓、白点", "高热不退", "张口困难、吞咽剧痛"],
    note: "若确诊细菌性扁桃体炎需抗生素，属处方药，请由医生判断。"
  },
  {
    id: "rhinitis", name: "过敏性鼻炎",
    aliases: ["鼻炎", "花粉症"],
    dept: "耳鼻喉科 / 变态反应科",
    kw: { "打喷嚏": 3, "流清涕": 3, "鼻痒": 3, "眼痒": 2, "花粉": 2, "尘螨": 2, "季节": 2, "晨起": 1 },
    otc: ["loratadine", "cetirizine"],
    rx_note: "鼻喷糖皮质激素（如布地奈德/糠酸莫米松）多为处方药，可咨询医生长期控制。",
    advice: ["远离过敏原，外出可戴口罩", "勤洗床品、控制尘螨", "症状重可记录发作规律供医生参考"],
    redflags: ["单侧鼻塞流涕长期不愈", "涕中带血"],
    note: "与感冒的区分：不发热、清水样涕、持续/反复、常伴眼痒。"
  },
  {
    id: "conjunctivitis", name: "结膜炎（红眼病）",
    aliases: ["结膜炎", "红眼病", "眼睛红"],
    dept: "眼科",
    kw: { "眼睛红": 3, "眼红": 3, "分泌物": 2, "异物感": 2, "流泪": 2, "眼痒": 2 },
    otc: ["artificial_tear"],
    rx_note: "细菌性结膜炎需抗生素滴眼液（处方药），请眼科确诊后使用；切勿共用毛巾。",
    advice: ["冷敷缓解不适", "勤洗手，不揉眼", "暂停佩戴隐形眼镜"],
    redflags: ["视力下降", "剧烈眼痛", "畏光明显"],
    note: "过敏性结膜炎以痒为主，可用抗过敏滴眼液（遵说明书）。"
  },
  {
    id: "migraine", name: "偏头痛",
    aliases: ["偏头痛", "半边头痛"],
    dept: "神经内科",
    kw: { "偏头痛": 3, "一侧头痛": 3, "搏动": 2, "跳痛": 2, "恶心": 1, "畏光": 2, "怕吵": 1, "先兆": 2 },
    otc: ["paracetamol", "ibuprofen"],
    advice: ["发作时在安静暗处休息", "记录发作诱因（睡眠/饮食/激素周期）", "止痛药每月使用勿过频，避免药物过量性头痛"],
    redflags: ["一生中最剧烈的头痛", "伴喷射性呕吐或肢体麻木", "50 岁后首次出现"],
    note: "止痛药在发作早期服用效果最好。"
  },
  {
    id: "tension_headache", name: "紧张性头痛",
    aliases: ["紧张性头痛", "紧箍感"],
    dept: "神经内科 / 疼痛科",
    kw: { "头痛": 2, "双侧": 1, "紧箍": 3, "压迫感": 2, "压力": 2, "熬夜": 2, "颈肩僵": 2, "长时间看屏幕": 2 },
    otc: ["paracetamol"],
    advice: ["规律作息，减少屏幕时间", "颈肩放松与热敷", "咖啡因适度"],
    redflags: ["头痛性质突然改变", "伴发热颈项强直"],
    note: "与偏头痛区分：多为双侧紧箍感、程度较轻、活动后不明显加重。"
  },
  {
    id: "gastroenteritis", name: "急性胃肠炎",
    aliases: ["胃肠炎", "吃坏肚子", "急性肠胃炎"],
    dept: "消化内科 / 急诊",
    kw: { "腹泻": 3, "呕吐": 2, "腹痛": 2, "恶心": 2, "水样便": 2, "吃坏": 3, "不洁饮食": 2 },
    otc: ["montmorillonite", "ors", "probiotics"],
    advice: ["清淡饮食，少量多次补水", "腹泻期间避免油腻奶制品", "注意手卫生"],
    redflags: ["便血或黑便", "高热", "明显脱水（口渴、尿少、乏力）", "持续呕吐无法进水"],
    note: "补液比止泻更重要；抗菌药为处方药，多数病毒性胃肠炎无需抗生素。"
  },
  {
    id: "dyspepsia", name: "功能性消化不良",
    aliases: ["消化不良", "胃胀", "积食"],
    dept: "消化内科",
    kw: { "腹胀": 3, "嗳气": 2, "早饱": 3, "消化不良": 3, "胃胀": 3, "食欲差": 1 },
    otc: ["domperidone", "hydrotalcite", "probiotics"],
    advice: ["少量多餐，细嚼慢咽", "减少油腻与产气食物", "餐后散步"],
    redflags: ["进行性消瘦", "吞咽困难", "贫血黑便"],
    note: "症状长期反复建议做胃镜排查。"
  },
  {
    id: "gerd", name: "胃食管反流",
    aliases: ["反酸", "烧心", "反流"],
    dept: "消化内科",
    kw: { "反酸": 3, "烧心": 3, "胸骨后": 2, "灼热": 2, "反流": 3, "嗳气": 1, "餐后": 1 },
    otc: ["omeprazole", "hydrotalcite"],
    advice: ["睡前 3 小时不进食", "抬高床头", "减少咖啡、酒、辛辣与高脂饮食"],
    redflags: ["吞咽困难或疼痛", "不明原因消瘦", "呕血黑便"],
    note: "奥美拉唑 OTC 连续使用不宜超过 14 天，长期反复请就医。"
  },
  {
    id: "constipation", name: "便秘",
    aliases: ["便秘", "排便困难"],
    dept: "消化内科 / 全科",
    kw: { "便秘": 3, "排便困难": 3, "大便干": 3, "排便次数少": 2, "用力排便": 2 },
    otc: ["lactulose", "glycerin"],
    advice: ["增加膳食纤维与饮水量", "固定排便时间，勿久忍", "规律运动"],
    redflags: ["便血", "排便习惯突然改变伴消瘦", "剧烈腹痛呕吐"],
    note: "开塞露适合应急，长期依赖会减弱自主排便反射。"
  },
  {
    id: "hemorrhoid", name: "痔疮",
    aliases: ["痔疮", "痔"],
    dept: "肛肠外科",
    kw: { "痔疮": 3, "肛门": 2, "鲜红血": 2, "便后滴血": 3, "肿物": 2, "久坐": 1 },
    otc: ["compound_phlegethon"],
    advice: ["温水坐浴", "多纤维多水防便秘", "避免久坐久蹲"],
    redflags: ["便血持续或血色暗红", "肛门剧痛伴肿块", "消瘦"],
    note: "便血务必先由医生排除其他病因，不要自行归因于痔疮。"
  },
  {
    id: "ulcer_stomatitis", name: "口腔溃疡（阿弗他溃疡）",
    aliases: ["口腔溃疡", "口疮"],
    dept: "口腔科",
    kw: { "口腔溃疡": 3, "口疮": 3, "嘴里疼": 2, "白点": 1, "进食痛": 2 },
    otc: ["mouthwash_chx", "watermelon_frost"],
    advice: ["避免辛辣烫食", "补充 B 族维生素与蔬果", "保持口腔清洁"],
    redflags: ["同一处溃疡超过 2 周不愈", "反复多处大面积溃疡", "伴外阴溃疡或眼部炎症"],
    note: "多数 1–2 周自愈；长期不愈的溃疡必须由口腔科检查。"
  },
  {
    id: "toothache", name: "牙痛 / 牙龈炎",
    aliases: ["牙痛", "牙疼", "牙龈"],
    dept: "口腔科",
    kw: { "牙痛": 3, "牙疼": 3, "牙龈出血": 2, "智齿": 2, "龋齿": 2, "冷热刺激": 2 },
    otc: ["ibuprofen", "paracetamol"],
    advice: ["止痛只是应急，牙源性问题必须由口腔科处理", "含温盐水保持清洁"],
    redflags: ["面部肿胀", "张口困难", "发热伴牙痛"],
    note: "止痛药掩盖不了进展中的牙髓/根尖感染，越早处理越简单。"
  },
  {
    id: "muscle_strain", name: "肌肉酸痛 / 软组织劳损",
    aliases: ["肌肉酸痛", "劳损", "运动后"],
    dept: "骨科 / 康复科",
    kw: { "肌肉酸痛": 3, "劳损": 2, "运动后": 2, "酸痛": 2, "用力后": 2, "搬重物": 2 },
    otc: ["ibuprofen", "diclofenac_gel"],
    advice: ["急性扭伤 48 小时内冷敷，之后热敷", "避免立即按摩或热敷急性肿胀处", "循序渐进恢复活动"],
    redflags: ["剧痛畸形无法活动", "明显肿胀迅速加重"],
    note: "外用 NSAIDs 凝胶全身吸收少，适合局部轻中度疼痛。"
  },
  {
    id: "stiff_neck", name: "落枕 / 颈部僵硬",
    aliases: ["落枕", "脖子僵"],
    dept: "康复科 / 骨科",
    kw: { "落枕": 3, "脖子": 2, "颈部僵硬": 3, "转头痛": 2, "睡醒": 1 },
    otc: ["diclofenac_gel"],
    advice: ["热敷 + 轻柔活动度练习", "调整枕头高度", "避免猛转头或强行掰颈"],
    redflags: ["手臂麻木无力", "伴发热头痛"],
    note: "多数 2–3 天自行缓解。"
  },
  {
    id: "dysmenorrhea", name: "痛经（原发性）",
    aliases: ["痛经", "月经疼"],
    dept: "妇科",
    kw: { "痛经": 3, "月经": 2, "下腹坠": 2, "经期": 2, "小腹疼": 2 },
    otc: ["ibuprofen", "paracetamol"],
    advice: ["热敷下腹部", "经前 1–2 天开始服药效果更好", "记录周期供妇科参考"],
    redflags: ["疼痛进行性加重", "非经期出血", "发热伴盆腔痛"],
    note: "继发性痛经（如子宫内膜异位症）需妇科评估，止痛药不能掩盖病因。"
  },
  {
    id: "motion_sickness", name: "晕动病",
    aliases: ["晕车", "晕船"],
    dept: "全科",
    kw: { "晕车": 3, "晕船": 3, "乘车恶心": 2, "头晕呕吐": 1 },
    otc: ["dimenhydrinate"],
    advice: ["坐前排、看远处地平线", "出发前 30–60 分钟服药", "途中避免阅读手机"],
    redflags: [],
    note: "茶苯海明服后会嗜睡，驾驶者禁用。"
  },
  {
    id: "dry_eye", name: "干眼 / 视疲劳",
    aliases: ["干眼", "视疲劳", "眼睛干"],
    dept: "眼科",
    kw: { "干眼": 3, "眼睛干": 3, "视疲劳": 2, "干涩": 3, "屏幕": 1, "异物感": 1 },
    otc: ["artificial_tear"],
    advice: ["20-20-20 法则：每 20 分钟看 6 米外 20 秒", "有意识完整眨眼", "屏幕略低于视线"],
    redflags: ["视力骤降", "眼红痛伴头痛"],
    note: "含防腐剂滴眼液不宜高频长期使用，可选无防腐剂型。"
  },
  {
    id: "urticaria", name: "荨麻疹（风团）",
    aliases: ["荨麻疹", "风团", "起包痒"],
    dept: "皮肤科 / 变态反应科",
    kw: { "荨麻疹": 3, "风团": 3, "瘙痒": 2, "起包": 2, "过敏": 2, "挠后隆起": 2 },
    otc: ["loratadine", "calamine"],
    advice: ["记录并回避可疑诱因（食物/药物/冷热）", "避免抓挠与热水烫洗", "冷敷止痒"],
    redflags: ["喉头发紧、声音嘶哑", "呼吸困难", "头晕乏力"],
    note: "出现呼吸/吞咽困难提示过敏性休克或喉头水肿，属急症。"
  },
  {
    id: "eczema", name: "湿疹",
    aliases: ["湿疹", "特应性皮炎"],
    dept: "皮肤科",
    kw: { "湿疹": 3, "红斑": 1, "脱屑": 2, "干燥": 1, "反复瘙痒": 2, "渗液": 2 },
    otc: ["hydrocortisone", "calamine"],
    advice: ["坚持足量使用保湿霜（最重要）", "温水短时洗澡", "穿纯棉衣物"],
    redflags: ["大量渗液化脓", "面积迅速扩大", "伴发热"],
    note: "弱效激素乳膏短期外用是湿疹一线方案，面部与皱褶处请遵医嘱。"
  },
  {
    id: "acne", name: "痤疮（痘痘）",
    aliases: ["痤疮", "痘痘", "粉刺"],
    dept: "皮肤科",
    kw: { "痘痘": 3, "痤疮": 3, "粉刺": 2, "油皮": 1, "闭口": 2 },
    otc: ["adapalene", "bpo"],
    advice: ["温和清洁，勿挤痘", "阿达帕林夜间薄涂并防晒", "坚持 8–12 周评估"],
    redflags: ["结节囊肿型痤疮", "用药后持续刺痛脱皮"],
    note: "中重度痤疮建议皮肤科制定方案（可能需要处方药）。"
  },
  {
    id: "sunburn", name: "轻度晒伤",
    aliases: ["晒伤", "晒红"],
    dept: "皮肤科 / 全科",
    kw: { "晒伤": 3, "晒红": 3, "脱皮": 1, "暴晒": 2, "日晒": 2 },
    otc: ["calamine"],
    advice: ["冷敷降温", "大量保湿", "后续严格防晒"],
    redflags: ["大面积水疱", "发热寒战"],
    note: "起疱勿挑破；数日内避免再次暴晒。"
  },
  {
    id: "insomnia", name: "短期失眠",
    aliases: ["失眠", "睡不着"],
    dept: "身心医学科 / 神经内科",
    kw: { "失眠": 3, "睡不着": 3, "入睡困难": 2, "早醒": 2, "多梦": 1, "夜里醒": 1 },
    otc: [],
    rx_note: "安眠药均为处方药且有依赖风险，必须由医生评估开具；褪黑素为保健品类，证据有限。",
    advice: ["固定起床时间（比固定入睡更有效）", "床只用于睡觉", "下午后戒咖啡因与酒精", "白天接受自然光照"],
    redflags: ["失眠超过 3 周", "伴随情绪持续低落或兴趣丧失"],
    note: "慢性失眠首选认知行为治疗（CBT-I），而非药物。"
  },
  {
    id: "cough_dry", name: "干咳（无痰）",
    aliases: ["干咳", "咳嗽无痰"],
    dept: "呼吸内科",
    kw: { "干咳": 3, "无痰": 2, "咳嗽": 2, "咽痒咳": 2, "夜间咳": 1 },
    otc: ["dextromethorphan"],
    advice: ["保持空气湿度", "避免冷空气与烟尘刺激"],
    redflags: ["咳嗽超过 2 周", "咯血", "胸痛、消瘦、盗汗"],
    note: "超过 2 周的咳嗽建议就诊排查，勿长期自行镇咳。"
  },
  {
    id: "cough_wet", name: "有痰咳嗽",
    aliases: ["咳嗽有痰", "痰多"],
    dept: "呼吸内科",
    kw: { "咳痰": 3, "痰多": 3, "有痰": 3, "黏稠": 2, "咳嗽": 1 },
    otc: ["ambroxol"],
    advice: ["多饮水稀释痰液", "学习有效咳痰姿势"],
    redflags: ["黄绿脓痰伴发热", "痰中带血", "喘息明显"],
    note: "有痰时不宜单用强力镇咳药，排痰比压住咳嗽重要。"
  },
  {
    id: "vertigo_general", name: "头晕 / 眩晕（轻症描述）",
    aliases: ["头晕", "眩晕"],
    dept: "神经内科 / 耳鼻喉科",
    kw: { "头晕": 3, "眩晕": 3, "天旋地转": 2, "站不稳": 1, "躺下翻身": 1 },
    otc: [],
    rx_note: "眩晕病因复杂（耳石症/前庭/脑血管等），多数药物为处方药，请先就医明确原因。",
    advice: ["发作时坐下或躺下防跌倒", "记录发作时长与诱发动作"],
    redflags: ["眩晕伴言语不清、复视、肢体无力", "剧烈头痛", "行走明显不稳"],
    note: "『天旋地转』的真眩晕与『头昏沉』的头晕指向完全不同，就医时请描述清楚。"
  },
  {
    id: "eye_strain", name: "视疲劳合并干眼",
    aliases: ["用眼过度"],
    dept: "眼科",
    kw: { "用眼过度": 3, "屏幕时间": 1, "酸胀": 1, "视疲劳": 2, "干涩": 2 },
    otc: ["artificial_tear"],
    advice: ["调整屏幕亮度与环境光一致", "20-20-20 法则", "睡眠充足"],
    redflags: ["视力持续下降", "眼痛头痛恶心"],
    note: "排除屈光问题（近视/散光）引起的疲劳，建议验光。"
  },
];

/* OTC / 外用药物信息卡 */
const DRUGS = [
  { id: "paracetamol", name: "对乙酰氨基酚", category: "解热镇痛", otc: true,
    use: "退热；缓解头痛、牙痛、肌肉痛、痛经等轻中度疼痛。",
    usage: "按说明书服用（成人常规一次 0.3–0.6g），24 小时不超过 4 次；退热连续使用不超过 3 天。",
    warn: ["肝功能不全者慎用", "服药期间严禁饮酒", "过量可致严重肝损伤"],
    extra: "许多复方感冒药都含此成分，切勿叠加服用。" },
  { id: "ibuprofen", name: "布洛芬", category: "解热镇痛 / NSAIDs", otc: true,
    use: "退热；头痛、牙痛、痛经、肌肉关节痛；抗炎。",
    usage: "按说明书服用，随餐或与食物同服减少胃刺激；连续用药不超过 5 天（止痛）/ 3 天（退热）。",
    warn: ["胃溃疡 / 肾功能不全者慎用", "阿司匹林哮喘者禁用", "水痘期间勿用"],
    extra: "与对乙酰氨基酚交替使用须间隔足够时间并遵说明书。" },
  { id: "compound_cold", name: "复方感冒药", category: "复方制剂", otc: true,
    use: "同时缓解鼻塞、流涕、发热、头痛等多种感冒症状。",
    usage: "按说明书，成人常规剂量，24 小时不超过规定次数。",
    warn: ["多含对乙酰氨基酚——不可与退烧药叠加", "含氯苯那敏：嗜睡，驾驶/高空作业者慎用", "高血压、甲亢、前列腺增生者慎用含伪麻黄碱成分"],
    extra: "看清成分表是使用复方感冒药的第一原则。" },
  { id: "loratadine", name: "氯雷他定", category: "二代抗组胺", otc: true,
    use: "过敏性鼻炎、荨麻疹、皮肤瘙痒。",
    usage: "按说明书每日一次。",
    warn: ["少数人仍会困倦", "严重肝功能不全者遵医嘱"],
    extra: "二代抗组胺药嗜睡副作用明显低于一代。" },
  { id: "cetirizine", name: "西替利嗪", category: "二代抗组胺", otc: true,
    use: "过敏性鼻炎、荨麻疹。",
    usage: "按说明书每日一次，可随餐服。",
    warn: ["个别使用者嗜睡", "肾功能不全者减量或遵医嘱"],
    extra: "同类药物单用即可，勿叠加两种抗组胺药。" },
  { id: "dextromethorphan", name: "右美沙芬", category: "中枢性镇咳", otc: true,
    use: "无痰干咳的对症镇咳。",
    usage: "按说明书服用。",
    warn: ["痰多者不宜（抑制排痰）", "勿超量使用（存在滥用风险）", "驾驶前慎用"],
    extra: "咳嗽超过 2 周请就医查明原因。" },
  { id: "ambroxol", name: "氨溴索", category: "祛痰药", otc: true,
    use: "痰液黏稠、咳痰困难。",
    usage: "按说明书服用，多饮水帮助化痰。",
    warn: ["偶见胃肠不适", "避免与强力镇咳药同时使用"],
    extra: "有痰咳嗽的关键是『稀释 + 排出』。" },
  { id: "loquat", name: "川贝枇杷膏（中成药示例）", category: "润肺止咳（中成药）", otc: true,
    use: "咽干咳嗽的对症缓解（按说明书适应证）。",
    usage: "按说明书。",
    warn: ["含糖，糖尿病者选无糖型并咨询", "不同厂家成分有差异"],
    extra: "中成药同样需按适应证使用。" },
  { id: "montmorillonite", name: "蒙脱石散", category: "止泻 / 吸附剂", otc: true,
    use: "成人及儿童的急性腹泻对症止泻。",
    usage: "按说明书冲服，宜空腹；与其他口服药间隔 1–2 小时。",
    warn: ["过量易便秘", "会吸附其他药物降低疗效"],
    extra: "腹泻的核心是补液防脱水（见口服补液盐）。" },
  { id: "ors", name: "口服补液盐 III（ORS）", category: "补液盐", otc: true,
    use: "腹泻 / 呕吐造成的轻度脱水，补充水电解质。",
    usage: "严格按说明比例冲调，少量多次饮用。",
    warn: ["勿自行加糖或果汁（改变渗透压）", "严重脱水需静脉补液（就医）"],
    extra: "WHO 推荐的家庭腹泻护理核心手段。" },
  { id: "probiotics", name: "双歧杆菌三联活菌（益生菌示例）", category: "微生态制剂", otc: true,
    use: "肠道菌群失调相关的腹泻、腹胀。",
    usage: "温水（≤40°C）送服；与抗菌药物间隔 2 小时。",
    warn: ["热水会杀死活菌", "免疫缺陷者遵医嘱"],
    extra: "不同菌株作用不同，按适应证选择。" },
  { id: "hydrotalcite", name: "铝碳酸镁", category: "抗酸 / 胃黏膜保护", otc: true,
    use: "胃酸过多、胃痛、烧心、反酸的对症缓解。",
    usage: "餐后 1–2 小时或睡前嚼服，按说明书；与其他药间隔 1–2 小时。",
    warn: ["长期大剂量使用注意铝、镁蓄积", "严重肾功能不全者慎用"],
    extra: "中和胃酸起效快，适合临时症状控制。" },
  { id: "omeprazole", name: "奥美拉唑", category: "质子泵抑制剂（抑酸）", otc: true,
    use: "反酸、烧心（胃食管反流）的短期对症。",
    usage: "按说明书；OTC 连续使用不宜超过 14 天。",
    warn: ["长期使用须医生指导", "与部分药物存在相互作用（如氯吡格雷）"],
    extra: "反复发作的反流应就医评估，而非长期自购抑酸药。" },
  { id: "domperidone", name: "多潘立酮", category: "促胃动力", otc: true,
    use: "腹胀、嗳气、消化不良。",
    usage: "餐前 15–30 分钟按说明书服用；症状缓解应及时停药。",
    warn: ["有心脏传导疾病史者慎用", "勿超剂量与延长疗程"],
    extra: "促动力药与抑酸药作用机制不同，按症状选择。" },
  { id: "lactulose", name: "乳果糖口服液", category: "渗透性通便", otc: true,
    use: "慢性便秘的温和通便。",
    usage: "按说明书；起效较慢（1–2 天），宜固定时间服用并多饮水。",
    warn: ["起始几天可能胀气", "糖尿病者按说明书咨询"],
    extra: "生活方式调整（纤维、水、运动）是根本。" },
  { id: "glycerin", name: "开塞露", category: "通便（外用）", otc: true,
    use: "便秘应急。",
    usage: "外用注入直肠，按说明书。",
    warn: ["不宜长期依赖", "频繁使用可能减弱排便反射"],
    extra: "应急之选，不是治疗方案。" },
  { id: "calamine", name: "炉甘石洗剂", category: "外用收敛止痒", otc: true,
    use: "荨麻疹、痱子等瘙痒性皮肤病的止痒。",
    usage: "摇匀后涂抹患处，每日数次。",
    warn: ["皮肤破损或渗液处不可用", "对炉甘石过敏者禁用"],
    extra: "温和物理止痒，儿童也常用（按说明书）。" },
  { id: "hydrocortisone", name: "氢化可的松乳膏（弱效）", category: "外用糖皮质激素（弱效）", otc: true,
    use: "湿疹、过敏性皮炎等短期局部对症。",
    usage: "薄涂患处，每日 1–2 次，短期使用（按说明书）。",
    warn: ["面部、褶皱处及大面积使用须遵医嘱", "不可用于皮肤感染处", "勿长期连续使用"],
    extra: "激素外用并不可怕，可怕的是不分强弱与部位乱用。" },
  { id: "compound_phlegethon", name: "复方角菜酸酯栓（痔疮用）", category: "肛肠外用", otc: true,
    use: "痔疮及肛裂的对症缓解。",
    usage: "按说明书纳入直肠。",
    warn: ["使用一周症状无改善应就医", "便血病因未明前勿自行归因于痔疮"],
    extra: "便血先就医排除，再对症处理。" },
  { id: "mouthwash_chx", name: "复方氯己定含漱液", category: "口腔含漱", otc: true,
    use: "牙龈炎、口腔黏膜炎等辅助清洁。",
    usage: "按说明书含漱，勿吞服。",
    warn: ["长期使用可能使牙齿着色、味觉改变", "与牙膏使用宜间隔"],
    extra: "口腔溃疡 2 周不愈务必就诊。" },
  { id: "watermelon_frost", name: "西瓜霜含片（中成药示例）", category: "利咽含片", otc: true,
    use: "咽痛、口腔溃疡的对症缓解。",
    usage: "按说明书含服。",
    warn: ["含糖型糖尿病者注意", "孕妇及体质特殊者按说明书"],
    extra: "含片在口腔局部起效，适合咽痛为主者。" },
  { id: "artificial_tear", name: "人工泪液（玻璃酸钠滴眼液）", category: "眼科润滑剂", otc: true,
    use: "干眼、视疲劳的润滑缓解。",
    usage: "按需滴用；高频使用者选无防腐剂型。",
    warn: ["开封后按说明书限期使用", "滴后闭眼片刻"],
    extra: "缓解干涩最基础、最安全的手段。" },
  { id: "diclofenac_gel", name: "双氯芬酸二乙胺乳胶剂", category: "外用 NSAIDs", otc: true,
    use: "肌肉、关节的局部疼痛与劳损。",
    usage: "薄涂患处并轻揉，每日 3–4 次。",
    warn: ["破损皮肤不可用", "勿接触眼与黏膜", "对双氯芬酸过敏者禁用"],
    extra: "外用途径全身暴露低，适合局部疼痛首选。" },
  { id: "adapalene", name: "阿达帕林凝胶", category: "外用维 A 酸类", otc: true,
    use: "以粉刺、丘疹为主的痤疮。",
    usage: "夜间洁面后薄涂，逐步建立耐受；白天严格防晒。",
    warn: ["初期可能有刺激、脱屑", "备孕/妊娠者禁用", "勿与高浓度酸类叠加"],
    extra: "痤疮外用方案的基石之一，坚持是关键。" },
  { id: "bpo", name: "过氧化苯甲酰", category: "外用抗菌（痤疮）", otc: true,
    use: "痤疮丙酸杆菌相关的炎性痘痘。",
    usage: "按说明书局部薄涂，注意漂白衣物风险。",
    warn: ["常见干燥刺激", "与维 A 酸类同涂需错开时间"],
    extra: "联合维 A 酸类是痤疮的经典组合。" },
  { id: "dimenhydrinate", name: "茶苯海明（乘晕宁）", category: "抗晕动", otc: true,
    use: "晕车、晕船的预防与缓解。",
    usage: "出发前 30–60 分钟按说明书服用。",
    warn: ["服后嗜睡，驾驶者禁用", "勿与其它镇静类同服"],
    extra: "预防性服用比晕了再吃有效得多。" },
];

/* 处方药科普卡 —— 只讲性质与就医指引, 不提供用法 */
const RX_CARDS = [
  { name: "阿莫西林 / 头孢类（青霉素类 / 头孢类抗生素）", category: "抗生素 · 处方药",
    note: "只对细菌感染有效，对病毒性感冒无效。滥用抗生素会导致耐药。使用前可能需皮试（青霉素类），必须由医生开具并按疗程服用。" },
  { name: "硝酸甘油", category: "心血管急救 · 处方药",
    note: "确诊冠心病者的急救药物。突发胸痛者未确诊前请直接拨打 120，不建议自行服用他人药物。" },
  { name: "沙丁胺醇气雾剂", category: "哮喘急救 · 处方药",
    note: "哮喘缓解用药。发作时按医生既往处方使用并立即就医；无确诊者突发喘息应挂急诊。" },
  { name: "二甲双胍", category: "降糖 · 处方药",
    note: "2 型糖尿病一线药物。剂量须个体化，凭处方使用并定期复查。" },
];

/* 快捷症状 chips（分析台） */
const QUICK_CHIPS = ["发热", "头痛", "咽痛", "咳嗽", "鼻塞", "流涕", "腹泻", "腹痛", "腹胀", "反酸", "烧心", "便秘", "瘙痒", "皮疹", "头晕", "失眠", "痛经", "牙痛", "眼干", "乏力"];

/* 相关方向映射 —— 直接受益于<3 个直接命中时, 补足"至少关联三种病症" */
const RELATED = {
  cold: ["flu", "pharyngitis", "rhinitis"],
  flu: ["cold", "pharyngitis", "cough_wet"],
  pharyngitis: ["cold", "flu", "ulcer_stomatitis"],
  rhinitis: ["cold", "conjunctivitis", "cough_dry"],
  conjunctivitis: ["dry_eye", "rhinitis", "eye_strain"],
  migraine: ["tension_headache", "vertigo_general", "toothache"],
  tension_headache: ["migraine", "stiff_neck", "insomnia"],
  gastroenteritis: ["dyspepsia", "gerd", "hemorrhoid"],
  dyspepsia: ["gerd", "gastroenteritis", "constipation"],
  gerd: ["dyspepsia", "gastroenteritis", "cough_dry"],
  constipation: ["hemorrhoid", "dyspepsia", "gerd"],
  hemorrhoid: ["constipation", "dyspepsia", "gastroenteritis"],
  ulcer_stomatitis: ["pharyngitis", "toothache", "cough_dry"],
  toothache: ["ulcer_stomatitis", "pharyngitis", "migraine"],
  muscle_strain: ["stiff_neck", "flu", "motion_sickness"],
  stiff_neck: ["muscle_strain", "tension_headache", "migraine"],
  dysmenorrhea: ["gastroenteritis", "constipation", "insomnia"],
  motion_sickness: ["vertigo_general", "gastroenteritis", "migraine"],
  dry_eye: ["eye_strain", "conjunctivitis", "migraine"],
  urticaria: ["eczema", "rhinitis", "sunburn"],
  eczema: ["urticaria", "sunburn", "acne"],
  acne: ["eczema", "urticaria", "sunburn"],
  sunburn: ["eczema", "urticaria", "acne"],
  insomnia: ["tension_headache", "gerd", "dyspepsia"],
  cough_dry: ["cough_wet", "cold", "flu"],
  cough_wet: ["cough_dry", "cold", "flu"],
  vertigo_general: ["migraine", "motion_sickness", "tension_headache"],
  eye_strain: ["dry_eye", "conjunctivitis", "tension_headache"],
};

/* 红旗急症对应的鉴别参考方向（仅急症描述命中时展示） */
const REDFLAG_RELATED = {
  "心血管": ["gerd", "muscle_strain", "flu"],
  "脑卒中": ["migraine", "vertigo_general", "tension_headache"],
  "气道": ["cough_dry", "rhinitis", "urticaria"],
  "蛛网膜下腔出血": ["migraine", "tension_headache", "vertigo_general"],
  "消化道出血": ["gerd", "dyspepsia", "hemorrhoid"],
  "意识": ["insomnia", "vertigo_general", "migraine"],
  "高热": ["flu", "cold", "pharyngitis"],
};
